name: Mi Primer Workflow

on: [push]

env:
  APP_ENV: production
  
jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Mostrar mensaje
        run: echo "Hola Paquito, GitHub Actions funciona!"

      - name: Mostrar segundo mensaje
        run: echo "Entorno: $APP_ENV!"
